RentAFlik_Main/src/beans/Products.java
package beans;
import java.io.IOException;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.*;
import javax.faces.component.UIComponent;
import javax.faces.component.html.HtmlCommandButton;
import javax.faces.component.html.HtmlDataTable;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;

import database.DAO;


@ManagedBean(name="productss", eager = true) 
@SessionScoped
@SuppressWarnings("unused")
public class Products implements Serializable{
	private static final long serialVersionUID = 1L;
	@Inject
	private business.ProductsBusinessInterface service;
	EnterpriseUser user;
	int id;
	String title;
	String genre;
	String leadAct;
	String studio;
	String director;
	int length;
	int year;
	double price = 3.5;
	String vidImg;
	public int testInput;
	public List<Product> productss = new ArrayList<>();

    /**
     * Default constructor. 
     */
    public Products() {
    	productss.add(new Product(1,"Dr. Seuss' The Grinch","Family","Benedict Cumberbatch","Illumination", "Yarrow Cheney", 90, 2019, 3.55, "TheGrinch.PNG"));
    	productss.add(new Product(2,"Robin Hood","Action","Taron Egerton","Lionsgate", "Otto Bathurst", 116, 2018, 3.55, "RobinHood.PNG"));
    	productss.add(new Product(3,"Ready Player One","Action","Tye Sheridan","Warner", "Steven Spielberg", 140, 2018, 3.55, "ReadyPlayerOne.PNG"));
    	productss.add(new Product(4,"Avengers: Infinity War","Action","Chris Hemsworth","BVHE", "Anthony Russo", 149, 2018, 3.55, "AvengersInfinityWar.PNG"));
    	productss.add(new Product(5,"The Lego Batman Movie","Family","Will Arnett","Warner", "Chris McKay", 124, 2017, 3.55, "LegoBatman.PNG"));
    	productss.add(new Product(6,"Johnny English Strikes Again","Comedy","Rowan Atkinson","Universal", "David Kerr", 88, 2019, 3.55, "JohnnyEnglish.PNG"));
    	productss.add(new Product(7,"Venom","Action","Tom Hardy","Sony", "Ruben Fleischer", 112, 2018, 3.55, "Venom.PNG"));
    	productss.add(new Product(8,"The Predator","Action","Boyd Holbrook","Fox", "Shane Black", 107, 2018, 3.55, "Predator.PNG"));
    }
	public Products(int id, String title, String genre, String leadAct, String studio, String director,
			int length, int year, double price, String vidImg) {
		this.id = id;
		this.title = title;
		this.genre = genre;
		this.leadAct = leadAct;
		this.studio = studio;
		this.director = director;
		this.length = length;
		this.year = year;
		this.price = price;
		this.vidImg = vidImg;
		
	}
	
	/**Method adds the project object from the form to a product list. 
	 * This list will be used to build the form table */
	public String addProd(ProductUser prod) throws SQLException{
        Product product = new Product(prod.getId(),prod.getTitle(),prod.getGenre(),prod.getLeadAct(),prod.getStudio(),prod.getDirector(),prod.getLength(),prod.getYear(),prod.getPrice(),prod.getVidImg());
        productss.add(product);
        service.setProducts(productss);
        DAO dao = new DAO(productss);
        return "AllProducts.xhtml?faces-redirect=true";
    }
    
	
	/**Method adds the project object from the form to a product list. 
	 * This list will be used to build the form table*/
	public String addProd(Products prod) throws SQLException{
        Product product = new Product(prod.getId(),prod.getTitle(),prod.getGenre(),prod.getLeadAct(),prod.getStudio(),prod.getDirector(),prod.getLength(),prod.getYear(),prod.getPrice(),prod.getVidImg());
        productss.add(product);
        service.setProducts(productss);
        DAO dao = new DAO(productss);
        return "added";
    }
	
	/**The search bar within the application compares against two of the product ID's. 
	 * If either search correctly passes then the console will output the appropriate
	 * product information based on the product ID that was established.*/
	public String searchTest() throws SQLException {
		if (testInput <= productss.size()) {
			System.out.println("Movie ID:" + productss.get(testInput).getId() + " Movie Title:"+ productss.get(testInput).getTitle() + " Movie Genre:" + productss.get(testInput).getGenre()
				+ " Lead Actor:" + productss.get(testInput).getLeadAct() + " Movie Studio:" + productss.get(testInput).getStudio() + " Movie Director:" + productss.get(testInput).getDirector()
				+ " Length:" + productss.get(testInput).getLength() + " Release Year:" + productss.get(testInput).getYear() + " Rental Price:$" + productss.get(testInput).getPrice());
		}
		
		else {
			System.out.println("Invalid ID");
		}
		return "Search.xhtml";
	}

	
	public Product getSearchProd() {
		if (testInput < productss.size()) {
			return productss.get(testInput);
		}
		
		else {
			System.out.println("Invalid ID");
			return null;
		}

	}
	
	/**Establishes the search variable with a getter and setter.*/
	public void setTestInput(int testInput) {
		this.testInput = testInput;
	}
	
	public int getTestInput() {
		return testInput;
	}
	
	/**This method returns the product list*/
	public List<Product> getProductss() {
		return productss;
	}
	
	/**Deletes the project object and updates the DAO*/
	public void deleteMovie(ActionEvent evt) {
		HtmlDataTable table = getParentDataTable((UIComponent)evt.getSource());
		//Object o = table.getRowData();
		int index = table.getRowIndex();
		System.out.println("I've got the row index " + index);
		try {
			productss.remove(index);
			
			DAO dao = new DAO(productss);
		} catch (SQLException e) {
			System.out.println("The table is empty");
		}
		//return "AllProducts.xhtml?faces-redirect=true";
	}
	

	/**Edit the product object and updates the DAO*/
	public void editMovie(ActionEvent evt) {
		HtmlDataTable table = getParentDataTable((UIComponent)evt.getSource());
		Object o = table.getRowData();
		
		System.out.println(o.toString());
		int index = table.getRowIndex();

		System.out.println("I've got the row index " + index);
		this.id = productss.get(index).getId();
		this.title = productss.get(index).getTitle();
		this.genre = productss.get(index).getGenre();
		this.leadAct = productss.get(index).getLeadAct();
		this.studio = productss.get(index).getStudio();
		this.director = productss.get(index).getDirector();
		this.length = productss.get(index).getLength();
		this.year = productss.get(index).getYear();
		this.price = productss.get(index).getPrice();
		this.vidImg = productss.get(index).getVidImg();
		try {
			productss.remove(index);
			
			DAO dao = new DAO(productss);
		} catch (SQLException e) {
			System.out.println("The table is empty");
		}
		//return "EditProduct.xhtml?faces-redirect=true";
	}	
	

	
/*	//Deletes the project object and updates the DAO
	public void testMovie(ActionEvent evt) {
		//HtmlDataTable table = getParentDataTable((UIComponent)evt.getSource());
		System.out.println(evt.getSource().toString());
		HtmlCommandButton bttn = (HtmlCommandButton) evt.getComponent();
		System.out.println(bttn.getId());
		bttn.getTabindex();
		System.out.println(bttn.getLabel());


		//Object o = table.getRowData();
		//int index = table.getRowIndex();
		System.out.println("I've got the row index ");
		
		//return "AllProducts.xhtml?faces-redirect=true";
	}*/
	
	//Deletes the project object and updates the DAO
		public String testMovie() {
			
			return "AllProducts.xhtml?faces-redirect=true";
		}
	
	
	private HtmlDataTable getParentDataTable(UIComponent compo) {
		if (compo == null) {
			return null;
		}
		if (compo instanceof HtmlDataTable) {
			return (HtmlDataTable) compo;
		}
		return getParentDataTable(compo.getParent());
	}

	
	/**Getters and Setters*/
	public void setId(int id) {
		this.id = id;
	}
	
	public int getId() {
		return id;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	
	public String getTitle() {
		return title;
	}
	public void setGenre(String genre) {
		this.genre = genre;
	}
	
	public String getGenre() {
		return genre;
	}	
	public void setLeadAct(String leadAct) {
		this.leadAct = leadAct;
	}
	
	public String getLeadAct() {
		return leadAct;
	}	

	public void setStudio(String studio) {
		this.studio = studio;
	}
	
	public String getStudio() {
		return studio;
	}
	
	public void setDirector(String director) {
		this.director = director;
	}
	
	public String getDirector() {
		return director;
	}
	
	public void setLength(int length) {
		this.length = length;
	}
	
	public int getLength() {
		return length;
	}
	
	public void setYear(int year) {
		this.year = year;
	}
	
	public int getYear() {
		return year;
	}
	
	public void setPrice(double price) {
		this.price = price;
	}
	
	public double getPrice() {
		return price;
	}
	
	public void setVidImg(String vidImg) {
		this.vidImg = vidImg;
	}
	
	public String getVidImg() {
		return vidImg;
	}
}

RentAFlik_Main/src/beans/RegisterBean.java
package beans;

public class RegisterBean {

 /** Applying all variables from registration.*/
 private String nickname;
 private String emailaddress;
 private String password;
 private String firstname;
 private String lastname;
 private String phone;
 
 /** Getters which are public strings and setters which are public voids. */
 public String getNickname() {
 return nickname;
 }
 public void setNickname(String nickname) {
 this.nickname = nickname;
 }
 public String getEmailAddress() {
 return emailaddress;
 }
 public void setEmailAddress(String emailaddress) {
 this.emailaddress = emailaddress;
 }
 public String getPassword() {
 return password;
 }
 public void setPassword(String password) {
 this.password = password;
 }
 public String getFirstName() {
 return firstname;
 }
 public void setFirstName(String firstname) {
 this.firstname = firstname;
 }
 public String getLastName() {
 return lastname;
 }
 public void setLastName(String lastname) {
 this.lastname = lastname;
 }
 public String getPhone() {
 return phone;
 }
 public void setPhone(String phone) {
 this.phone = phone;
 }
}

RentAFlik_Main/WebContent/About.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
				<h3 style="text-align:center;">We rent movies at a great price!!!</h3>
	</body> 
	</ui:define>	
</ui:composition>
</html>

RentAFlik_Main/WebContent/AllProducts.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">


<h:head>
	<script type="text/javascript">
	function handleClick(evt){
		System.out.println("made it here");
		var node = evt.target || evt.srcElement;
		if (node.name == 'edit'){
			node.value = "Modify";
			System.out.println("made it here")
			}
	}
	</script>
	
		<style>
	body {background-color: #acc;}
	h1   {color: blue;}
	
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 16px;
  text-decoration: none;
  font-size:16px;
}

li a:hover {
  background-color: #111111;
}
	
#SearchLabel {
   display: block;
  color: white;
  text-align: right;
  padding: 16px;
  text-decoration: none;
  font-size:25px;
}	
#SearchTextBox {
  display: block;
  padding: 16px;
  float: left;
  margin: 0;
}		
#logoImg {
  padding: 5px;
  display: block;
}	



#videoList {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  width:100%;
  margin: auto;
  overflow-x:scroll;
  overflow-y:hidden;
  background-color: #888888;
}

#vidImg {
  flex: 0 0 auto;
  margin: auto;
  padding: 3px;
}
.order-table{   
	border-collapse:collapse;
	border:3px solid #000000;
}

.order-table-header{
	text-align:center;
	background:none repeat scroll 0 0 #E5E5E5;
	border-bottom:1px solid #000000;
	padding:10px;

}

.order-table-odd-row{
	text-align:center;
	background:none repeat scroll 0 0 #FFFFFFF;
	border-top:1px solid #444444;
}

.order-table-even-row{
	text-align:center;
	background:none repeat scroll 0 0 #F9F9F9;
	border-top:1px solid #444444;
}

	</style>
</h:head> 
	<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
	<!-- This form is used to add products -->
		<h:form id="newProductForm">
	
		<!-- Creates the table below the form with populated data -->
			<h:dataTable value = "#{productss.productss}" var = "odr"
            styleClass = "order-table"
            headerClass = "order-table-header"
            rowClasses = "order-table-odd-row,order-table-even-row" 
            >
            <h:column>    				
               <f:facet name = "header">Movie ID</f:facet>    				
               #{odr.id}
            </h:column>            
            <h:column>    				
               <f:facet name = "header">Movie Title</f:facet>    				
               #{odr.title}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Genre</f:facet>
               #{odr.genre}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Lead Actor</f:facet>
               #{odr.leadAct}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Production Studio</f:facet>
               #{odr.studio}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Director</f:facet>
               #{odr.director}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Length</f:facet>
               #{odr.length}
            </h:column>
            <h:column>
               <f:facet name = "header">Year</f:facet>
               #{odr.year}
            </h:column>
            <h:column>
               <f:facet name = "header">Rental Price $</f:facet>
               #{odr.price}
            </h:column>
            <h:column>
               <f:facet name = "header">Video Image File</f:facet>
               #{odr.vidImg}
            </h:column>
            <h:column>
               <p:commandButton actionListener="#{productss.editMovie}" value="Edit" update="newProductForm"/>
            </h:column>
            <h:column>
                <p:growl id="message" showDetail="true" />
    			<p:commandButton value="Delete" actionListener="#{productss.deleteMovie}" update="newProductForm" >
        		<p:confirm header="Confirmation" message="Are you sure?" icon="pi pi-exclamation-triangle" />
    			</p:commandButton>

    			<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
        		<p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check"/>
        		<p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="pi pi-times"/>
    			</p:confirmDialog>     
            </h:column>
            </h:dataTable>	
            <h3>Edit Form</h3>
		

		<h:panelGrid columns="3">
		<h:outputLabel value="Movie ID:" /> 
		<h:inputText value="#{productss.id}" /><br /><br />
		<h:outputLabel value="Movie Title:" /> 
		<h:inputText value="#{productss.title}" /><br /><br />
		<h:outputLabel value="Genre:" />
		<h:inputText value="#{productss.genre}" /><br /><br />
		<h:outputLabel value="Lead Actor:" />
		<h:inputText value="#{productss.leadAct}" /><br /><br />
		<h:outputLabel value="Studio:" />
		<h:inputText value="#{productss.studio}" /><br /><br />
		<h:outputLabel value="Director:" />
		<h:inputText value="#{productss.director}" /><br /><br />
		<h:outputLabel value="Length:" />
		<h:inputText value="#{productss.length}" /><br /><br />
		<h:outputLabel value="Release Year:" />
		<h:inputText value="#{productss.year}" /><br /><br />
		<h:outputLabel value="Rental Price $:" />
		<h:outputLabel value="#{productss.price}" /><br /><br />
		<h:outputLabel value="Video Image File (.PNG):" />
		<h:inputText value="#{productss.vidImg}" /><br /><br />
		</h:panelGrid>
		<h:commandButton action="#{productss.addProd(productss)}" value="Update Product" />&nbsp;&nbsp; <h:button value="Add Products" outcome="NewProduct.xhtml" />
		</h:form><p></p>
		
</body> 
</ui:define>	
</ui:composition> 
</html>

RentAFlik_Main/WebContent/Contact.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
				<h3 style="text-align:center;">1-800-rnt-flik</h3>
	</body> 
	</ui:define>	
</ui:composition>
</html>

RentAFlik_Main/WebContent/LoginError.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head><title>Login Error Page</title></h:head> 
<body style="background-color: #acc"> 
			<h1 style="text-align:center;">Rent-A-Flik</h1>
			<div align="center"> 
				<p>Please enter a user name or password that is authorized to access this
        			application. For this application, this means a user that has been
        			created in the <code>file</code> realm and has been assigned to the
    			<em>group</em> of <code>RafUser</code>.</p>
    			<p><a href="MainForm.xhtml">Return to Login</a></p>		
			</div>
			<h5 style="text-align:center;">@Copyright Rent-A-Flik</h5>
</body> 
</html>

RentAFlik_Main/WebContent/LoginForm.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
> 

<h:head><title>Login Form Page</title></h:head> 
<h:body style="background-color: #acc"> 
			<h1 style="text-align:center;">Rent-A-Flik</h1>
			<div align="center"> 			
				<form  method="post" action="j_security_check">
					<h:panelGrid columns="2">
						Username: <h:inputText style="width:100px;" id="j_username" autocomplete="off" />
						Password: <h:inputSecret style="width:100px;" id="j_password" autocomplete="off" />
						
					</h:panelGrid>
					<h:commandButton style="text-align:center; margin:2px;" type="submit" value="Submit"/><br></br>
					<a href="UpdatedRegisrationForm.jsp" style="text-align:center; padding:8px;">Registration</a>
					
				</form>
				<h:messages />
			</div>
			<h5 style="text-align:center;">@Copyright Rent-A-Flik</h5>
			
			


</h:body> 

</html>

RentAFlik_Main/WebContent/LoginPage.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>Login Page</title>
</h:head> 

	<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 			

<h:form id="loginForm">
<!--The login page takes in the user submitted data and calls on the login()
	function with the User.java class. A standard inputText is used for the 
	username while inputSecret is used for the password as per standard with 
	passwords. -->
	<h:outputLabel value="username" /> &nbsp;
	<h:inputText style="width:100px;" value="#{EnterpriseUser.userName}" /><br /><br />
	<h:outputLabel value="password"/> &nbsp;
	<h:inputSecret style="width:100px;" value="#{EnterpriseUser.password}"></h:inputSecret><br /><br />
	<h:commandButton action="#{EnterpriseUser.login}" value="Login"></h:commandButton>&nbsp;
	<h:button value="Register" outcome="UpdatedRegisrationForm.jsp"></h:button>
</h:form>
</body> 
    </ui:define>	
	</ui:composition> 

</html>

RentAFlik_Main/WebContent/NewRegistration.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 
     <ui:define name="tags"></ui:define>
<h:head>
<title> JSF Form Page</title>
</h:head> 
 <ui:composition>
<body> 
<form action="MainFormController" method="post">
<label>User Name:</label>
<h:inputText value="#{EnterpriseRegistration.userName}" name = "userName"/><br/>
<label>Email Address:</label>
<h:inputText value="#{EnterpriseRegistration.emailAddress}" name="emailAddress"/><br/>
<label>Password:</label>
<h:inputSecret value="#{EnterpriseRegistration.passWord}" name="password"/><br/>
<label>First Name:</label>
<h:inputText value="#{EnterpriseRegistration.firstName}" name="firstName"/><br/>
<label>LastName:</label>
<h:inputText value="#{EnterpriseRegistration.lastName}" name = "lastName"/><br/>
<input type="submit" value="Submit"/>
</form>
</body> 
</ui:composition>
</html>

RentAFlik_Main/WebContent/News.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
				<h3 style="text-align:center;">No News Today!</h3>
	</body> 
	</ui:define>	
</ui:composition>
</html>

RentAFlik_Main/WebContent/Search.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
		<h:panelGrid columns="2">
		<h:graphicImage value="/images/#{productss.searchProd.vidImg}"/> <br></br>
		<h:outputLabel value="Movie Title:" /> 
		<h:outputLabel value="#{productss.searchProd.title}" />
		<h:outputLabel value="Genre:" />
		<h:outputLabel value="#{productss.searchProd.genre}" />
		<h:outputLabel value="Lead Actor:" />
		<h:outputLabel value="#{productss.searchProd.leadAct}" />
		<h:outputLabel value="Studio:" />
		<h:outputLabel value="#{productss.searchProd.studio}" />
		<h:outputLabel value="Director:" />
		<h:outputLabel value="#{productss.searchProd.director}" />
		<h:outputLabel value="Length:" />
		<h:outputLabel value="#{productss.searchProd.length}" />
		<h:outputLabel value="Release Year:" />
		<h:outputLabel value="#{productss.searchProd.year}" />
		<h:outputLabel value="Rental Price $:" />
		<h:outputLabel value="#{productss.searchProd.price}" />
		</h:panelGrid>
	</body> 
	</ui:define>	
</ui:composition>
</html>

RentAFlik_Main/WebContent/SuccessfulLogin.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 
<!--Basic successful login screen. Upon merging the application will
	redirect to the logged in state of the application.-->
<h:head>
<title>Successful Login</title>
</h:head> 
	<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
	Welcome! You successfully logged into our service!
	</body> 
 	</ui:define>	
	</ui:composition> 
</html>

RentAFlik_Main/WebContent/TestResponse.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

<body>
<p>Hello #{EnterpriseRegistration.firstName} #{EnterpriseRegistration.lastName}</p>
</body>
</html>